### ISSUE TITLE
推送精灵无法添加到群里

### ISSUE THREAD

**Issue by Yunkou** [tans/push-bot#1]
RT：求方法

**Comment by Yunkou** [comment]
目前的方法是，重新建群是可以的。

**Comment by Yunkou** [comment]
重新发起群聊之后，推送机器人没有发token 导致 群聊Api 不能使用

**Comment by chengjiahua** [comment]
一样的问题  获取不到token 导致群聊api不可用

**Comment by tans** [comment]
因为机器人是企业微信， 所以只能拉近现有的企微群。 

建议重新发起一个群聊。重新发起群聊后记得群上发一条消息，这样机器人才能发现新的群聊。

**Comment by tans** [comment]
> 重新发起群聊之后，推送机器人没有发token 导致 群聊Api 不能使用

发个消息入群， 就能后激活新的群聊。

**Comment by Yunkou** [comment]
> > 重新发起群聊之后，推送机器人没有发token 导致 群聊Api 不能使用
> 
> 发个消息入群， 就能后激活新的群聊。

建议把这个写到 ReadMe里面，刚开始有有点懵

**Comment by tans** [comment]
已加上机器人如何入群的说明
