### ISSUE TITLE
运行 node bot.js且配置好.env后，有警告正常么？

### ISSUE THREAD

**Issue by fcbhank** [tans/push-bot#5]
如题，在添加机器人企业微信好友获得token后，直接使用提供的接口是没问题的。但在配置好.env文件后，运行 `node bot.js` 依然出现如下警告，请问这个是为什么呢？
---
```shell
WARN No endpoint when starting grpc client, 10 retry left. Reconnecting in 10 seconds...

```

**Comment by fcbhank** [comment]
@tans

**Comment by tans** [comment]
你这个是没有token吧

**Comment by fcbhank** [comment]
@tans 
有`token`的，也正常配置在了`.env`文件中

该`token`能正常使用接口`https://push.bot.qw360.cn/send/:token`推送消息

**Comment by tans** [comment]
env的token不是推送精灵的token， 那是wechaty的token。
